In [3]:
import pandas as pd
pd.set_option('display.max_columns', None)
df = pd.read_parquet('merchants_reference.parquet')
df

,merchant_id,merchant_name,mcc,merchant_country,recurring_capable
0,MER_000000,Google Ads,7311,Ireland,True
1,MER_000001,Meta Ads,7311,Ireland,True
2,MER_000002,TikTok Ads,7311,Singapore,True
3,MER_000003,Yandex Direct,7311,Russia,True
4,MER_000004,LinkedIn Ads,7311,Ireland,True
...,...,...,...,...,...
2160,MER_002160,Hotel/Lodging(Cod_9271,3705,Kazakhstan,False
2161,MER_002161,Hotel/Lodging(Cod_1934,3705,Kazakhstan,False
2162,MER_002162,Airline(Code3236_1010,3236,Kazakhstan,False
2163,MER_002163,Airline(Code3236_2766,3236,Kazakhstan,False
2164,MER_002164,Airline(Code3236_6865,3236,Kazakhstan,False

In [4]:
import pandas as pd
pd.set_option('display.max_columns', None)
df_2 = pd.read_parquet('business_cards_MDQ.parquet')
df_2

,transaction_date,transaction_timestamp,transaction_amount_kzt,mcc,merchant_id,channel,bank_name,country,card_number,card_tier,tokenized,is_recurring
0,2025-10-01,2025-10-01 00:00:00,180976,7372,MER_000007,online,Kaspi,US,5228592291438845,Business,False,True
1,2025-10-01,2025-10-01 00:00:00,153206,7372,MER_000006,online,Home Credit Bank,US,5201495142193372,Business,False,True
2,2025-10-01,2025-10-01 00:00:00,197106,7372,MER_000007,online,Home Credit Bank,US,5201492177677288,Business,False,True
3,2025-10-01,2025-10-01 00:01:00,189598,7372,MER_000008,online,Kaspi,US,5176513443697635,Business,False,True
4,2025-10-01,2025-10-01 00:03:00,700571,7311,MER_000003,online,Halyk,Russia,5100611967455520,Business,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
2997588,2026-03-31,2026-03-31 23:05:10,28768,7311,MER_000000,online,Kaspi,Kazakhstan,5531518705038741,Business,True,False
2997589,2026-03-31,2026-03-31 23:15:14,49167,8931,MER_000817,online,Kaspi,Kazakhstan,5176515154725265,Business,True,False
2997590,2026-03-31,2026-03-31 23:21:08,21450,5733,MER_000132,online,Forte Bank,Kazakhstan,5168269308290061,Business,False,False
2997591,2026-03-31,2026-03-31 23:27:19,49854,5085,MER_000335,online,Halyk,Kazakhstan,5438819609301282,Business,True,False
2997592,2026-03-31,2026-03-31 23:59:30,492544,7399,MER_000865,online,BCC Bank,Kazakhstan,5402334058638921,Business,False,False

In [5]:
import pandas as pd
pd.set_option('display.max_columns', None)
df_3 = pd.read_parquet('consumer_cards_MDQ.parquet')
df_3

,transaction_date,transaction_timestamp,transaction_amount_kzt,mcc,merchant_id,channel,bank_name,country,card_number,card_tier,tokenized,is_recurring
0,2025-10-01,2025-10-01 00:04:00,4788,4814,MER_000064,online,Alatau City Bank,Kazakhstan,5263907968824596,Standard,False,True
1,2025-10-01,2025-10-01 00:10:00,5240,4814,MER_000063,online,Bank RBK,Kazakhstan,5119023663984986,Standard,False,True
2,2025-10-01,2025-10-01 00:12:00,4576,4814,MER_000066,online,Kaspi,Kazakhstan,5228590878155154,Standard,False,True
3,2025-10-01,2025-10-01 00:37:00,6078,4814,MER_000063,online,Home Credit Bank,Kazakhstan,5338472125333693,Standard,False,True
4,2025-10-01,2025-10-01 00:37:00,6042,4814,MER_000065,online,Kaspi,Kazakhstan,5531514712394557,Affluent,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
9832482,2026-03-31,2026-03-31 23:34:37,815,5462,MER_001385,online,Kaspi,Germany,5531515947565911,Standard,True,False
9832483,2026-03-31,2026-03-31 23:40:14,30385,3295,MER_001565,POS,Forte Bank,Kazakhstan,5368291138944152,Standard,False,False
9832484,2026-03-31,2026-03-31 23:40:28,21928,4814,MER_001714,POS,Bank RBK,Kazakhstan,5188844727829511,Affluent,True,False
9832485,2026-03-31,2026-03-31 23:41:41,135564,5541,MER_000037,POS,Halyk,Kazakhstan,5486731633496247,Standard,False,False
9832486,2026-03-31,2026-03-31 23:48:24,3557,4899,MER_001127,online,Forte Bank,Kazakhstan,5368296896271219,Standard,False,False